import { BreakPoints, ClassName, FlexAligns, FlexDirections, FlexJustifies, Flexs, FlexWrap } from "../types";

type FlexFlexClass = Record<BreakPoints, Record<Flexs, ClassName>>;
type FlexDirectionClass = Record<BreakPoints, Record<FlexDirections, ClassName>>;
type FlexJustifyClass = Record<BreakPoints, Record<FlexJustifies, ClassName>>;
type FlexAlignClass = Record<BreakPoints, Record<FlexAligns, ClassName>>;
type FlexWrapClass = Record<BreakPoints, Record<FlexWrap, ClassName>>;

export const GLOBAL_FLEX_ALIGN: FlexAlignClass = {
    base: {
        'start': 'items-start',
        'end': 'items-end',
        'end-safe': 'items-end-safe',
        'center': 'items-center',
        'center-safe': 'items-center-safe',
        'baseline': 'items-baseline',
        'baseline-last': 'items-baseline-last',
        'stretch': 'items-stretch',
    },
    sm: {
        'start': 'sm:items-start',
        'end': 'sm:items-end',
        'end-safe': 'sm:items-end-safe',
        'center': 'sm:items-center',
        'center-safe': 'sm:items-center-safe',
        'baseline': 'sm:items-baseline',
        'baseline-last': 'sm:items-baseline-last',
        'stretch': 'sm:items-stretch',
    },
    md: {
        'start': 'md:items-start',
        'end': 'md:items-end',
        'end-safe': 'md:items-end-safe',
        'center': 'md:items-center',
        'center-safe': 'md:items-center-safe',
        'baseline': 'md:items-baseline',
        'baseline-last': 'md:items-baseline-last',
        'stretch': 'md:items-stretch',
    },
    lg: {
        'start': 'lg:items-start',
        'end': 'lg:items-end',
        'end-safe': 'lg:items-end-safe',
        'center': 'lg:items-center',
        'center-safe': 'lg:items-center-safe',
        'baseline': 'lg:items-baseline',
        'baseline-last': 'lg:items-baseline-last',
        'stretch': 'lg:items-stretch',
    },
    xl: {
        'start': 'xl:items-start',
        'end': 'xl:items-end',
        'end-safe': 'xl:items-end-safe',
        'center': 'xl:items-center',
        'center-safe': 'xl:items-center-safe',
        'baseline': 'xl:items-baseline',
        'baseline-last': 'xl:items-baseline-last',
        'stretch': 'xl:items-stretch',
    },
    "2xl": {
        'start': '2xl:items-start',
        'end': '2xl:items-end',
        'end-safe': '2xl:items-end-safe',
        'center': '2xl:items-center',
        'center-safe': '2xl:items-center-safe',
        'baseline': '2xl:items-baseline',
        'baseline-last': '2xl:items-baseline-last',
        'stretch': '2xl:items-stretch',
    }
};
export const GLOBAL_FLEX_DIRECTION: FlexDirectionClass = {
    base: {
        'row': 'flex-row',
        'row-reverse': 'flex-row-reverse',
        'col': 'flex-col',
        'col-reverse': 'flex-col-reverse',
    },
    sm: {
        'row': 'sm:flex-row',
        'row-reverse': 'sm:flex-row-reverse',
        'col': 'sm:flex-col',
        'col-reverse': 'sm:flex-col-reverse',
    },
    md: {
        'row': 'md:flex-row',
        'row-reverse': 'md:flex-row-reverse',
        'col': 'md:flex-col',
        'col-reverse': 'md:flex-col-reverse',
    },
    lg: {
        'row': 'lg:flex-row',
        'row-reverse': 'lg:flex-row-reverse',
        'col': 'lg:flex-col',
        'col-reverse': 'lg:flex-col-reverse',
    },
    xl: {
        'row': 'xl:flex-row',
        'row-reverse': 'xl:flex-row-reverse',
        'col': 'xl:flex-col',
        'col-reverse': 'xl:flex-col-reverse',
    },
    "2xl": {
        'row': '2xl:flex-row',
        'row-reverse': '2xl:flex-row-reverse',
        'col': '2xl:flex-col',
        'col-reverse': '2xl:flex-col-reverse',
    }
}
export const GLOBAL_FLEX_CONTROL: FlexFlexClass = {
    base: {
        'none': 'flex-none',
        'auto': 'flex-auto',
        'initial': 'flex-initial',
        1: 'flex-1',
        2: 'flex-2',
        3: 'flex-3',
        4: 'flex-4',
        5: 'flex-5',
        6: 'flex-6',
        7: 'flex-7',
        8: 'flex-8',
        9: 'flex-9',
        10: 'flex-10',
        11: 'flex-11',
        12: 'flex-12',
    },
    sm: {
        'none': 'sm:flex-none',
        'auto': 'sm:flex-auto',
        'initial': 'sm:flex-initial',
        1: 'sm:flex-1',
        2: 'sm:flex-2',
        3: 'sm:flex-3',
        4: 'sm:flex-4',
        5: 'sm:flex-5',
        6: 'sm:flex-6',
        7: 'sm:flex-7',
        8: 'sm:flex-8',
        9: 'sm:flex-9',
        10: 'sm:flex-10',
        11: 'sm:flex-11',
        12: 'sm:flex-12',
    },
    md: {
        'none': 'md:flex-none',
        'auto': 'md:flex-auto',
        'initial': 'md:flex-initial',
        1: 'md:flex-1',
        2: 'md:flex-2',
        3: 'md:flex-3',
        4: 'md:flex-4',
        5: 'md:flex-5',
        6: 'md:flex-6',
        7: 'md:flex-7',
        8: 'md:flex-8',
        9: 'md:flex-9',
        10: 'md:flex-10',
        11: 'md:flex-11',
        12: 'md:flex-12',
    },
    lg: {
        'none': 'lg:flex-none',
        'auto': 'lg:flex-auto',
        'initial': 'lg:flex-initial',
        1: 'lg:flex-1',
        2: 'lg:flex-2',
        3: 'lg:flex-3',
        4: 'lg:flex-4',
        5: 'lg:flex-5',
        6: 'lg:flex-6',
        7: 'lg:flex-7',
        8: 'lg:flex-8',
        9: 'lg:flex-9',
        10: 'lg:flex-10',
        11: 'lg:flex-11',
        12: 'lg:flex-12',
    },
    xl: {
        'none': 'xl:flex-none',
        'auto': 'xl:flex-auto',
        'initial': 'xl:flex-initial',
        1: 'xl:flex-1',
        2: 'xl:flex-2',
        3: 'xl:flex-3',
        4: 'xl:flex-4',
        5: 'xl:flex-5',
        6: 'xl:flex-6',
        7: 'xl:flex-7',
        8: 'xl:flex-8',
        9: 'xl:flex-9',
        10: 'xl:flex-10',
        11: 'xl:flex-11',
        12: 'xl:flex-12',
    },
    "2xl": {
        'none': '2xl:flex-none',
        'auto': '2xl:flex-auto',
        'initial': '2xl:flex-initial',
        1: '2xl:flex-1',
        2: '2xl:flex-2',
        3: '2xl:flex-3',
        4: '2xl:flex-4',
        5: '2xl:flex-5',
        6: '2xl:flex-6',
        7: '2xl:flex-7',
        8: '2xl:flex-8',
        9: '2xl:flex-9',
        10: '2xl:flex-10',
        11: '2xl:flex-11',
        12: '2xl:flex-12',
    }
}
export const GLOBAL_FLEX_JUSTIFY: FlexJustifyClass = {
    base: {
        'start': 'justify-start',
        'end': 'justify-end',
        'end-safe': 'justify-end-safe',
        'center': 'justify-center',
        'center-safe': 'justify-center-safe',
        'between': 'justify-between',
        'around': 'justify-around',
        'evenly': 'justify-evenly',
        'stretch': 'justify-stretch',
        'baseline': 'justify-baseline',
        'normal': 'justify-normal',
    },
    sm: {
        'start': 'sm:justify-start',
        'end': 'sm:justify-end',
        'end-safe': 'sm:justify-end-safe',
        'center': 'sm:justify-center',
        'center-safe': 'sm:justify-center-safe',
        'between': 'sm:justify-between',
        'around': 'sm:justify-around',
        'evenly': 'sm:justify-evenly',
        'stretch': 'sm:justify-stretch',
        'baseline': 'sm:justify-baseline',
        'normal': 'sm:justify-normal',
    },
    md: {
        'start': 'md:justify-start',
        'end': 'md:justify-end',
        'end-safe': 'md:justify-end-safe',
        'center': 'md:justify-center',
        'center-safe': 'md:justify-center-safe',
        'between': 'md:justify-between',
        'around': 'md:justify-around',
        'evenly': 'md:justify-evenly',
        'stretch': 'md:justify-stretch',
        'baseline': 'md:justify-baseline',
        'normal': 'md:justify-normal',
    },
    lg: {
        'start': 'lg:justify-start',
        'end': 'lg:justify-end',
        'end-safe': 'lg:justify-end-safe',
        'center': 'lg:justify-center',
        'center-safe': 'lg:justify-center-safe',
        'between': 'lg:justify-between',
        'around': 'lg:justify-around',
        'evenly': 'lg:justify-evenly',
        'stretch': 'lg:justify-stretch',
        'baseline': 'lg:justify-baseline',
        'normal': 'lg:justify-normal',
    },
    xl: {
        'start': 'xl:justify-start',
        'end': 'xl:justify-end',
        'end-safe': 'xl:justify-end-safe',
        'center': 'xl:justify-center',
        'center-safe': 'xl:justify-center-safe',
        'between': 'xl:justify-between',
        'around': 'xl:justify-around',
        'evenly': 'xl:justify-evenly',
        'stretch': 'xl:justify-stretch',
        'baseline': 'xl:justify-baseline',
        'normal': 'xl:justify-normal',
    },
    "2xl": {
        'start': '2xl:justify-start',
        'end': '2xl:justify-end',
        'end-safe': '2xl:justify-end-safe',
        'center': '2xl:justify-center',
        'center-safe': '2xl:justify-center-safe',
        'between': '2xl:justify-between',
        'around': '2xl:justify-around',
        'evenly': '2xl:justify-evenly',
        'stretch': '2xl:justify-stretch',
        'baseline': '2xl:justify-baseline',
        'normal': '2xl:justify-normal',
    }
};
export const GLOBAL_FLEX_WRAP: FlexWrapClass = {
    base: {
        'wrap': 'flex-wrap',
        'wrap-reverse': 'flex-wrap-reverse',
        'nowrap': 'flex-nowrap',
    },
    sm: {
        'wrap': 'sm:flex-wrap',
        'wrap-reverse': 'sm:flex-wrap-reverse',
        'nowrap': 'sm:flex-nowrap',
    },
    md: {
        'wrap': 'md:flex-wrap',
        'wrap-reverse': 'md:flex-wrap-reverse',
        'nowrap': 'md:flex-nowrap',
    },
    lg: {
        'wrap': 'lg:flex-wrap',
        'wrap-reverse': 'lg:flex-wrap-reverse',
        'nowrap': 'lg:flex-nowrap',
    },
    xl: {
        'wrap': 'xl:flex-wrap',
        'wrap-reverse': 'xl:flex-wrap-reverse',
        'nowrap': 'xl:flex-nowrap',
    },
    "2xl": {
        'wrap': '2xl:flex-wrap',
        'wrap-reverse': '2xl:flex-wrap-reverse',
        'nowrap': '2xl:flex-nowrap',
    }
}